### ISSUE TITLE
Split mesh using a splitting plane

### ISSUE THREAD

**Issue by themmes** [mikedh/trimesh#235]
I want to split a mesh using a plane, similar to `cross_section` but returning both halves of the mesh as closed meshes instead of the polyline boundary of the intersection surface. I wrote the following code to achieve this:

```
def split_mesh(mesh, plane_origin, plane_normal):
    """
    Splits mesh by intersection with a plane, 
    returns closed mesh for positive and negative side of plane 
    """
    plane_normal = unit_vector(plane_normal)
    
    polyline, triangles_edge = trimesh.intersections.mesh_plane(bbox_mesh, 
                                                           plane_origin= plane_origin, 
                                                           plane_normal= plane_normal, 
                                                           return_faces=True)
    
    vertices_negative = []
    vertices_positive = []
    for vertex_id, vertex in enumerate(bbox_mesh.vertices):
        # TODO: add threshold
        signed_distance = np.dot(plane_normal, np.subtract(vertex, plane_origin))
        if signed_distance < 0:
            vertices_negative.append(vertex_id)
        else:
            vertices_positive.append(vertex_id)
    
    triangles_negative = []
    triangles_positive = []
    # For each triangle check how many points on either side of the plane
    for triangle in bbox_mesh.faces:
        triangle_negative_check = [vertex_id in vertices_negative for vertex_id in triangle]
        # If all points on the negative side this triangle is not affected
        if all(triangle_negative_check):
            triangles_negative.append(np.array(bbox_mesh.vertices[triangle]))
        elif any(triangle_negative_check):
            # Get section line for this triangle on edge
            section = polyline[np.all(np.isin(bbox_mesh.faces[triangles_edge], np.array(triangle)), axis=1)][0]
            assert section.shape == (2,3)
            # If two points on negative side
            if sum(triangle_negative_check) == 2:
                vertex_1, vertex_2 = bbox_mesh.vertices[triangle[triangle_negative_check]]
                triangles_negative.extend(unordered_to_triangles([section[0], section[1], vertex_1, vertex_2]))
                vertex_3 = bbox_mesh.vertices[triangle[np.logical_not(triangle_negative_check)]]
                triangles_positive.append(np.vstack([section[0], section[1], vertex_3]))
            elif sum(triangle_negative_check) == 1:
                vertex_3 = bbox_mesh.vertices[triangle[triangle_negative_check]]
                triangles_negative.append(np.vstack([section[0], section[1], vertex_3]))
                vertex_1, vertex_2 = bbox_mesh.vertices[triangle[np.logical_not(triangle_negative_check)]]
                triangles_positive.extend(unordered_to_triangles([section[0], section[1], vertex_1, vertex_2]))
        # If all points on the positive side this triangle is not affected
        else:
            triangles_positive.append(np.array(bbox_mesh.vertices[triangle]))
            
    # Get triangulation of the split surface
    vertices_splitsurface = []
    for a, b in polyline:
        for vertex in [a,b]:
            if tuple(vertex) not in vertices_splitsurface:
                vertices_splitsurface.append(tuple(vertex))

    triangles_splitsurface = unordered_to_triangles(vertices_splitsurface)
    
    # Add triangles of split surface to both the positive and negative side
    triangles_negative.extend(triangles_splitsurface)
    triangles_positive.extend(triangles_splitsurface)
    
    # Create Trimesh from triangles for positive and negative
    mesh_negative = trimesh.Trimesh(*to_face_indices(triangles_negative))
    mesh_positive = trimesh.Trimesh(*to_face_indices(triangles_positive))
    
    return mesh_positive, mesh_negative
```

Would it be useful to improve and create a pull request, or is there a much more simple way to achieve this with trimesh?

Looking forward to your reply!

**Comment by mikedh** [comment]
Hey, actually a super recent PR (https://github.com/mikedh/trimesh/pull/229 ) introduced [`slice_mesh_plane`](https://github.com/mikedh/trimesh/blob/master/trimesh/intersections.py#L389-L559) which I think does the same thing except only returning faces on the positive side of the plane. It is extremely quick when I've profiled it, if you need both sides you could potentially create a `slice_mesh_bidirectional` which caches the dots for both slicing operations and returns two meshes. 

Give it a spin and see if it meets your needs as well. If it not, PR's are always welcome!

**Comment by themmes** [comment]
Hmm.. I did not want to call the same function twice. Because, it would compute the intersections etc twice. But getting stuck as triangles are not properly created.

```
# from .constants import log, tol
from trimesh.constants import log, tol
from trimesh import geometry

def slice_mesh_plane_bidirectional(mesh,
                                   plane_normal,
                                   plane_origin,
                                   cached_dots=None):
    """
    Slice a mesh with a plane, returning a new mesh that is the
    portion of the original mesh to the positive normal side of the plane
    Parameters
    ---------
    mesh : Trimesh object
        Source mesh to slice
    plane_normal : (3,) float
        Normal vector of plane to intersect with mesh
    plane_origin:  (3,) float
        Point on plane to intersect with mesh
    cached_dots : (n, 3) float
        If an external function has stored dot
        products pass them here to avoid recomputing
    Returns
    ----------
    new_mesh : Trimesh object
        Sliced mesh
    """

    from . import base

    # If passed invalid input, return None
    if mesh is None:
        return None

    # check input plane
    plane_normal = np.asanyarray(plane_normal,
                                 dtype=np.float64)
    plane_origin = np.asanyarray(plane_origin,
                                 dtype=np.float64)

    if plane_origin.shape != (3,) or plane_normal.shape != (3,):
        raise ValueError('Plane origin and normal must be (3,)!')

    if cached_dots is not None:
        dots = cached_dots
    else:
        # dot product of each vertex with the plane normal indexed by face
        # so for each face the dot product of each vertex is a row
        # shape is the same as mesh.faces (n,3)
        dots = np.dot(plane_normal,
                      (mesh.vertices - plane_origin).T)[mesh.faces]
        
    # Find vertex orientations w.r.t. faces for all triangles:
    #  -1 -> vertex "inside" plane (positive normal direction)
    #   0 -> vertex on plane
    #   1 -> vertex "outside" plane (negative normal direction)
    signs = np.zeros(mesh.faces.shape, dtype=np.int8)
    signs[dots < -tol.merge] = 1
    signs[dots > tol.merge] = -1

    # Find all triangles that intersect this plane
    # onedge <- indices of all triangles intersecting the plane
    # inside <- indices of all triangles "inside" the plane (positive normal)
    # outside <- indices of all triangles "outside" the plane (negative normal)
    signs_sum = signs.sum(axis=1)
    signs_asum = np.abs(signs).sum(axis=1)

    onedge = np.logical_and(signs_asum >= 2,
                            np.abs(signs_sum) <= 1)
    positive = np.logical_or(signs_sum == -3,
                           np.logical_and(signs_sum == -1, signs_asum == 1))
    negative = np.logical_or(signs_sum == 3, 
                           np.logical_and(signs_sum == 1, signs_asum == -1))
    
    # Automatically include all faces that are "inside"
    positive_faces = mesh.faces[positive]
    negative_faces = mesh.faces[negative]

    # Separate faces on the edge into two cases: those which will become
    # quads (two on a side of the plane) and those which will become triangles
    # (one vertex on a side of the plane)
    # For a face where one side is quad, the other side is tri and vice versa
    cut_triangles = mesh.triangles[onedge]
    cut_faces_quad = mesh.faces[np.logical_and(onedge, signs_sum < 0)]
    cut_faces_tri = mesh.faces[np.logical_and(onedge, signs_sum >= 0)]
    cut_signs_quad = signs[np.logical_and(onedge, signs_sum < 0)]
    cut_signs_tri = signs[np.logical_and(onedge, signs_sum >= 0)]

    # If no faces to cut, the surface is not in contact with this plane.
    # Thus, return the mesh as is
    if len(cut_faces_quad) + len(cut_faces_tri) == 0:
        return mesh

    # Extract the intersections of each triangle's edges with the plane
    o = cut_triangles                               # origins
    d = np.roll(o, -1, axis=1) - o                  # directions
    num = (plane_origin - o).dot(plane_normal)      # compute num/denom
    denom = np.dot(d, plane_normal)
    denom[denom == 0.0] = 1e-12                     # prevent division by zero
    dist = np.divide(num, denom)
    # intersection points for each segment
    int_points = np.einsum('ij,ijk->ijk', dist, d) + o

    # Initialize the array of new vertices with the current vertices
    new_vertices = mesh.vertices
    num_new_vertices = len(new_vertices)
    
    def form_quads(quad_int_points, num_quads, cut_faces_quad, quad_int_inds, num_new_vertices):
        quad_int_verts = cut_faces_quad[
            np.stack((range(num_quads), range(num_quads)), axis=1),
            np.stack(((quad_int_inds + 1) % 3, (quad_int_inds + 2) % 3), axis=1)]

        # Fill out new quad faces with the intersection points as vertices
        new_quad_faces = np.append(
            quad_int_verts,
            np.arange(num_new_vertices,
                      num_new_vertices +
                      2 * num_quads).reshape(num_quads, 2), axis=1)
        
        new_tri_faces_from_quads = geometry.triangulate_quads(new_quad_faces)
        
        # Extract correct intersection points from int_points and order them in
        # the same way as they were added to faces
        new_quad_vertices = quad_int_points[
            np.stack((range(num_quads), range(num_quads)), axis=1),
            np.stack((((quad_int_inds + 2) % 3).T, quad_int_inds.T),
                     axis=1), :].reshape(2 * num_quads, 3)

        return new_quad_vertices, new_tri_faces_from_quads
    
    # Handle the case where a new quad is formed by the intersection
    # First, extract the intersection points belonging to a new quad
    positive_quad_int_points = int_points[(signs_sum < 0)[onedge], :, :]
    negative_quad_int_points = int_points[(signs_sum >= 0)[onedge], :, :]
    positive_num_quads = len(positive_quad_int_points)
    negative_num_quads = len(negative_quad_int_points)
    
    if positive_num_quads > 0:
        # Extract the vertex on the outside of the plane, then get the vertices
        # (in CCW order of the inside vertices)
        positive_quad_int_inds = np.where(cut_signs_quad == 1)[1]
        
        new_quad_vertices, new_tri_faces_from_quads = form_quads(positive_quad_int_points, 
                                                                 positive_num_quads,
                                                                 cut_faces_quad,
                                                                 positive_quad_int_inds,
                                                                 num_new_vertices)
        positive_vertices = np.append(new_vertices, new_quad_vertices, axis=0)
        positive_faces = np.append(positive_faces, new_tri_faces_from_quads, axis=0)
    
    if negative_num_quads > 0:
        # Extract the vertex on the outside of the plane, then get the vertices
        # (in CCW order of the inside vertices)
        negative_quad_int_inds = np.where(cut_signs_tri == -1)[1]
        
        new_quad_vertices, new_tri_faces_from_quads = form_quads(negative_quad_int_points,
                                                                 negative_num_quads,
                                                                 cut_faces_tri,
                                                                 negative_quad_int_inds,
                                                                 num_new_vertices)
        negative_vertices = np.append(new_vertices, new_quad_vertices, axis=0)
        negative_faces = np.append(negative_faces, new_tri_faces_from_quads, axis=0)
    
    def form_triangles(tri_int_points, num_tris, cut_faces_tri, tri_int_inds, num_new_vertices):
        tri_int_verts = cut_faces_tri[range(
            num_tris), tri_int_inds].reshape(num_tris, 1)

        # Fill out new triangles with the intersection points as vertices
        new_tri_faces = np.append(
            tri_int_verts,
            np.arange(num_new_vertices,
                      num_new_vertices +
                      2 * num_tris).reshape(num_tris, 2),
            axis=1)

        print(new_tri_faces)
        
        # Extract correct intersection points and order them in the same way as
        # the vertices were added to the faces
        new_tri_vertices = tri_int_points[
            np.stack((range(num_tris), range(num_tris)), axis=1),
            np.stack((tri_int_inds.T, ((tri_int_inds + 2) % 3).T),
                     axis=1),
            :].reshape(2 * num_tris, 3)
        
        print(new_tri_vertices)

        return new_tri_vertices, new_tri_faces
    
    # Handle the case where a new triangle is formed by the intersection
    # First, extract the intersection points belonging to a new triangle
    positive_tri_int_points = int_points[(signs_sum >= 0)[onedge], :, :]
    negative_tri_int_points = int_points[(signs_sum < 0)[onedge], :, :]
    positive_num_tris = len(positive_tri_int_points)
    negative_num_tris = len(negative_tri_int_points)
    
    if positive_num_tris > 0:
        # Extract the single vertex for each triangle inside the plane and get the
        # inside vertices (CCW order)
        positive_tri_int_inds = np.where(cut_signs_tri == -1)[1]
        
        new_tri_vertices, new_tri_faces = form_triangles(positive_tri_int_points,
                                                                     positive_num_tris,
                                                                     cut_faces_tri,
                                                                     positive_tri_int_inds,
                                                                     num_new_vertices)
        positive_vertices = np.append(positive_vertices, new_tri_vertices, axis=0)
        positive_faces = np.append(positive_faces, new_tri_faces, axis=0)
    
    if negative_num_tris > 0:
        # Extract the single vertex for each triangle inside the plane and get the
        # inside vertices (CCW order)
        negative_tri_int_inds = np.where(cut_signs_quad == 1)[1]
        
        new_tri_vertices, new_tri_faces = form_triangles(negative_tri_int_points,
                                                                     negative_num_tris,
                                                                     cut_faces_quad,
                                                                     negative_tri_int_inds,
                                                                     num_new_vertices)
        negative_vertices = np.append(negative_vertices, new_tri_vertices, axis=0)
        negative_faces = np.append(negative_faces, new_tri_faces, axis=0)
        
    # TODO: implement capping ends
    def cap_end():
        return

    # new mesh for positive and negative vertices, faces
    unique, inverse = np.unique(positive_faces,
                                return_inverse=True)
    positive_mesh = base.Trimesh(vertices=positive_vertices[unique],
                            faces=inverse.reshape((-1, 3)),
                            process=False)
    
    unique, inverse = np.unique(negative_faces,
                                return_inverse=True)
    negative_mesh = base.Trimesh(vertices=negative_vertices[unique],
                            faces=inverse.reshape((-1, 3)),
                            process=False)

    return [positive_mesh, negative_mesh]
```

**Comment by themmes** [comment]
Anyway, I tried your other approach:

<details>
<summary>linestrings_to_polygon</summary>
<p>
import networkx as nx

def linestrings_to_polygon(linestrings):
    """
    Return valid polygon for unordered set of 3D linestrings in numpy array (n,2,3)
    """
    n_vertices, dim = linestrings.shape[0] * linestrings.shape[1], linestrings.shape[2]
    vertices = linestrings.reshape(n_vertices, dim)
    uniq, index, inv = np.unique(vertices.round(decimals=4), return_index=True, return_inverse=True, axis=0)
    assert uniq.shape[0] == vertices.shape[0] / 2
    linestrings_indices = inv.reshape(inv.shape[0]//2, 2)
    
    G = nx.from_edgelist([(a,b) for a,b in linestrings_indices])
    polygon = shapely.geometry.Polygon(vertices[index][[a for a, b in nx.find_cycle(G)]])
    assert polygon.is_valid
    return polygon
</p>
</details>

Implementation similar to your suggestion, including capping open ends.

```python
import trimesh.intersections

def slice_mesh_plane_bidirectional(mesh, plane_normal, plane_origin):
    # Compute positive side of plane
    dots_cache = np.dot(plane_normal, (mesh.vertices - plane_origin).T)[mesh.faces]
    positive = trimesh.intersections.slice_mesh_plane(mesh,
                                                     plane_normal=plane_normal,
                                                     plane_origin=plane_origin,
                                                     cached_dots=dots_cache)
    
    # Compute negative side of plane
    dots_cache *= -1
    negative = trimesh.intersections.slice_mesh_plane(mesh,
                                                     plane_normal=-plane_normal,
                                                     plane_origin=plane_origin,
                                                     cached_dots=dots_cache)
    
    # Compute the cap
    cap = trimesh.intersections.mesh_plane(mesh,
                                       plane_normal=-plane_normal, 
                                       plane_origin=plane_origin, 
                                       return_faces=False, 
                                       cached_dots=dots_cache)
    
    polygon = linestrings_to_polygon(cap)
    # Triangulate the cap and add to both sides
    cap_vertices, cap_faces = trimesh.creation.triangulate_polygon(polygon)
    print(cap_vertices.shape, cap_faces.shape)
    
    # Append cap to positive mesh
    positive_vertices, n_positive_vertices = positive.vertices, len(positive.vertices)
    np.append(positive_vertices, cap_vertices, axis=0)
    positive_faces = positive.faces
    np.append(positive_faces, cap_faces+n_positive_vertices, axis=0)
    # Construct negative mesh
    positive_mesh = trimesh.base.Trimesh(vertices=positive_vertices, faces=positive_faces)
    
    # Append cap to negative mesh
    negative_vertices, n_negative_vertices = negative.vertices, len(negative.vertices)
    np.append(negative_vertices, cap_vertices, axis=0)
    negative_faces = negative.faces
    np.append(negative_faces, cap_faces+n_negative_vertices, axis=0)
    # Construct negative mesh
    negative_mesh = trimesh.base.Trimesh(vertices=negative_vertices, faces=negative_faces)

    return [positive_mesh, negative_mesh]
```

For some reason the `trimesh.creation.triangulate_polygon` turns the polygon below:

```
POLYGON Z ((12 3203 77.16970170640745, 12 3268.200439631641 76.69979984979925, 12 9204 33.92028410374769, 29.59697960548745 9204 34.05965652518653, 4502 9204 69.48219224307377, 4502 9145.442381733686 69.90421905297444, 4502 3203 112.7316098457339, 4427.295926242265 3203 112.1399351444852, 12 3203 77.16970170640745))
```

into two arrays of the following shapes

```
vertices (280, 2) 
faces (410, 3)
```

**Comment by mikedh** [comment]
Oh, you probably don't have to implement `linestrings_to_polygon` yourself, if you just do `trimesh.load_path(sections)` it will give you a `Path3D` object (or if you want to call the specific function, it's `trimesh.path.io.misc.lines_to_path`).  If you transform the sections onto the plane either manually or through `path.to_planar`, It will then have `path.polygons_full` constructed for you. 

As for the result of `triangulate_polygon`, that looks correct- the vertices are 2D because it's coming from a planar polygon, you just need to `np.column_stack` it with zeros to use it in a 3D mesh.

**Comment by themmes** [comment]
Does it sample the area of the polygon? My polygon only has 8 vertices.

**Comment by mikedh** [comment]
Yeah triangle will insert vertices to get a better triangulation, you can [look at their args](http://dzhelil.info/triangle/quality.html). The one that makes the most difference seems to be minimum angle; I just changed the default to 30 degrees. 


However your example poly was doing crazy things because of a Z component, it seems like it might have screwed up indexing inside triangle: 
![broken](https://user-images.githubusercontent.com/1403074/47578597-c5c07600-d917-11e8-97d3-2ad99067dff7.png)

I just pushed a fix which checks and removes the Z before running triangulation:
![better](https://user-images.githubusercontent.com/1403074/47578603-c9ec9380-d917-11e8-82cf-c5bd6f9dc1ce.png)

It should release once the build from commit https://github.com/mikedh/trimesh/commit/842652aa80ee0f746643d56269bc4ff1668f1dd6 finishes.

**Comment by mikedh** [comment]
BTW the test script to generate those images:
```
In [1]: ws = 'POLYGON Z ((12 3203 77.16970170640745, 12 3268.200439631
   ...: 641 76.69979984979925, 12 9204 33.92028410374769, 29.596979605
   ...: 48745 9204 34.05965652518653, 4502 9204 69.48219224307377, 450
   ...: 2 9145.442381733686 69.90421905297444, 4502 3203 112.731609845
   ...: 7339, 4427.295926242265 3203 112.1399351444852, 12 3203 77.169
   ...: 70170640745))'

In [2]: from shapely.wkt import loads

In [3]: poly = loads(ws)

In [5]: import trimesh

In [6]: v,f =trimesh.creation.triangulate_polygon(poly)

In [7]: v.shape
Out[7]: (94, 2)

In [8]: f.shape
Out[8]: (133, 3)

In [10]: import matplotlib.pyplot as plt

In [11]: for i in v[trimesh.geometry.faces_to_edges(f)]:
    ...:     plt.plot(*i.T, color='k')
    ...:     

In [12]: trimesh.path.polygons.plot_polygon(poly)

```

**Comment by mikedh** [comment]
Closing for now as I think two calls to `slice_mesh_plane` is an adequate solution, though feel free to re-open or PR. Thanks for the report!

**Comment by HakuG** [comment]
I'm still having problems with capping. I get an open mesh if I call slice_mesh_plane, but I need a closed mesh. 

Is there a way to take the Path3D from the cap and make that into a Polygon3D that we can then merge with the mesh?

**Comment by mikedh** [comment]
Hey, probably the best way is to triangulate a section in 2D then append. Here's an example that looks decent, but is not watertight due to the inserted vertices in the 2D triangulation:

![cap](https://user-images.githubusercontent.com/1403074/49182131-647d2f80-f327-11e8-911b-d3986c22871d.png)

```
import trimesh
import numpy as np


if __name__ == '__main__':
    m = trimesh.load('models/featuretype.STL')

    # the plane we're using
    normal = trimesh.unitize([1,1,1])
    origin = m.center_mass

    # get a section as a Path3D object
    s = m.section(plane_origin=origin,
                  plane_normal=normal)

    # transform the Path3D onto the XY plane so we can triangulate
    on_plane, to_3D = s.to_planar()

    # triangulate each closed region of the 2D cap
    v, f = [], []
    for polygon in on_plane.polygons_full:
        tri = trimesh.creation.triangulate_polygon(polygon)
        v.append(tri[0])
        f.append(tri[1])
        
    # append the regions and re- index
    vf, ff = trimesh.util.append_faces(v, f)
    # three dimensionalize polygon vertices
    vf = np.column_stack((vf, np.zeros(len(vf))))
    # transform points back to original mesh frame
    vf = trimesh.transform_points(vf, to_3D)
    # flip winding of faces for cap
    ff = np.fliplr(ff)

    # the mesh for the planar cap
    cap = trimesh.Trimesh(vf, ff)

    # get the uncapped slice
    sliced = m.slice_plane(plane_origin=origin,
                           plane_normal=normal)

    # append the cap to the sliced mesh
    capped = sliced + cap


    capped.show()
```

**Comment by HakuG** [comment]
I'm confused as to why it's not watertight? is there a way to make it watertight? I'm looking to create something like the "split" functionality in slic3r and cura.

**Comment by mikedh** [comment]
It's because the triangulation of the cap inserts vertices, making the adjacency incorrect when you just append the two. Things like calculated volume or inertia (which relies on a surface integral) or cross sections will still be correct. 

To fix adjacency on the capped mesh to make it fully watertight you could split faces in the sliced mesh where there are new vertices. You could also play with the [triangulation args](http://dzhelil.info/triangle/delaunay.html) to see if there is a mode which doesn't insert vertices:

```
import trimesh
import numpy as np


if __name__ == '__main__':
    m = trimesh.load('models/featuretype.STL')

    # the plane we're using
    normal = trimesh.unitize([1,1,1])
    origin = m.center_mass

    # get a section as a Path3D object
    s = m.section(plane_origin=origin,
                  plane_normal=normal)

    # transform the Path3D onto the XY plane so we can triangulate
    on_plane, to_3D = s.to_planar()

    # triangulate each closed region of the 2D cap
    v, f = [], []
    for polygon in on_plane.polygons_full:
        tri = trimesh.creation.triangulate_polygon(polygon,
                                                   triangle_args='pq0D')
        v.append(tri[0])
        f.append(tri[1])
        
    # append the regions and re- index
    vf, ff = trimesh.util.append_faces(v, f)
    # three dimensionalize polygon vertices
    vf = np.column_stack((vf, np.zeros(len(vf))))
    # transform points back to original mesh frame
    vf = trimesh.transform_points(vf, to_3D)
    # flip winding of faces for cap
    ff = np.fliplr(ff)

    # the mesh for the planar cap
    cap = trimesh.Trimesh(vf, ff)

    # get the uncapped slice
    sliced = m.slice_plane(plane_origin=origin,
                           plane_normal=normal)

    # append the cap to the sliced mesh
    capped = sliced + cap

    capped._validate = True
    capped.process()
    
    # highlight faces with incorrect adjacency
    trimesh.repair.broken_faces(capped, color=[255,0,0,255])

    capped.show(smooth=False)
```

**Comment by lvnsn** [comment]
It appears that the following arguments avoid inserting additional vertices:

tri = trimesh.creation.triangulate_polygon(polygon,
                                                   triangle_args='p', allow_boundary_steiner=False)

**Comment by mikedh** [comment]
Nice find! I should probably add a `cap` kwarg, or secondary method.

**Comment by diegopradogesto** [comment]
> I'm confused as to why it's not watertight? is there a way to make it watertight? I'm looking to create something like the "split" functionality in slic3r and cura.

Hey @HakuG , great to hear that you plan to do something like the cutting plane in Cura. As part of that team, I'd love to have something like that. I think it's a nice idea to build a plugin that does that and make it available through our Marketplace. In fact, we now include trimesh in our builds, so using the library is a good choice. Let me know if I can help.
