### ISSUE TITLE
OBJ/MTL: Material information not used

### ISSUE THREAD

**Issue by mfeldt** [mikedh/trimesh#475]
When reading a .obj + associated .mtl file, the material information is apparently ignored.
While the loading itself works (verified by trimesh.util.attach_to_log() and watching the error after removing the .mtl file), the rendered structure when using .show() is always grey.  

It works with the fuze example that has an associated jpg map, but apparently not with simple material definitions.

**Comment by mikedh** [comment]
Yeah, currently this is true. The OBJ loader is being rewritten, which we'll hopefully release mid-July in https://github.com/mikedh/trimesh/pull/467

**Comment by jackd** [comment]
@mfeldt Is this resolved in the latest `release/major` branch? If not, can you provide an example failure case?

**Comment by mikedh** [comment]
Hey @jackd I think the new OBJ leader is currently transferring the properties correctly to `SimpleMaterial.ambient` etc, but `trimesh.viewer.windowed` and `trimesh.rendering` isn't using those values the moment and is still showing previews in the default grey.

**Comment by jackd** [comment]
Oh yeah. I currently have super hacky stuff which creates single-pixel values after loading.

```python
def fix_visual(visual, nv):
    from PIL import Image
    if isinstance(visual, trimesh.visual.ColorVisuals):
        return
    material = visual.material
    assert(hasattr(material, 'image'))
    if material.image is None and material.diffuse is not None:
        image = np.array(material.diffuse)
        image = (image*255).astype(dtype=np.uint8).reshape((1, 1, 3))
        image = Image.fromarray(image)
        material.image = image
    if visual.uv is None:
        visual.uv = np.zeros((nv, 2))


def fix_geometry_visuals(geometry):
    visual = getattr(geometry, 'visual', [])
    nv = geometry.vertices.shape[0]
    if hasattr(visual, '__iter__'):
        for v in visual:
            fix_visual(v, nv)
    else:
        fix_visual(visual, nv)


def fix_scene_visuals(scene):
    geometry = scene.geometry
    if hasattr(geometry, 'values'):
        for v in geometry.values():
            fix_geometry_visuals(v)
    elif hasattr(geometry, '__iter__'):
        for v in geometry:
            fix_geometry_visuals(v)
    else:
        fix_geometry_visuals(v)
```

**Comment by mfeldt** [comment]
> @mfeldt Is this resolved in the latest `release/major` branch? If not, can you provide an example failure case?

Apparently not @jackd . Loading my files leads to

```
a=trimesh.load('step.obj')
specified material not loaded!
specified material not loaded!
specified material not loaded!
specified material not loaded!
specified material not loaded!
a.show()
```

and things still looking grey!

I'm attaching the files as .txt so that github accepts them...
[step.mtl.txt](https://github.com/mikedh/trimesh/files/3367239/step.mtl.txt)
[step.obj.txt](https://github.com/mikedh/trimesh/files/3367240/step.obj.txt)

**Comment by jackd** [comment]
Submitted a PR fixing the names with spaces issue. The renderer still won't render these materials by default, but if you hack the mesh with the code below it should get your something reasonable.

```python
import trimesh
import numpy as np


def fix_visual(visual, nv):
    from PIL import Image
    if isinstance(visual, trimesh.visual.ColorVisuals):
        return
    material = visual.material
    assert(hasattr(material, 'image'))
    if material.image is None and material.diffuse is not None:
        image = np.array(material.diffuse)
        image = (image*255).astype(dtype=np.uint8).reshape((1, 1, 3))
        image = Image.fromarray(image)
        material.image = image
    if visual.uv is None:
        visual.uv = np.zeros((nv, 2))


def fix_geometry_visuals(geometry):
    visual = getattr(geometry, 'visual', [])
    nv = geometry.vertices.shape[0]
    if hasattr(visual, '__iter__'):
        for v in visual:
            fix_visual(v, nv)
    else:
        fix_visual(visual, nv)


def fix_scene_visuals(scene):
    geometry = scene.geometry
    if hasattr(geometry, 'values'):
        for v in geometry.values():
            fix_geometry_visuals(v)
    elif hasattr(geometry, '__iter__'):
        for v in geometry:
            fix_geometry_visuals(v)
    else:
        fix_geometry_visuals(v)

a = trimesh.load('step.obj')
if isinstance(a, trimesh.Scene):
    fix_scene_visuals(a)
else:
    fix_geometry_visuals(a)
a.show()
```

**Comment by jackd** [comment]
Update: this looks to work nicely without the `fix_*` hacks above with the 3.0 release

**Comment by choward232** [comment]
Still showing 'specified material not loaded' for me, is there any way to at least quiet the error message? Thanks!

**Comment by jackd** [comment]
Interesting. Doesn't happen for me, but if that's the only issue you can try `trimesh.util.log.setLevel('ERROR')`

**Comment by choward232** [comment]
Great, that at least quieted the error. Thanks

**Comment by mikedh** [comment]
Closing for now as new OBJ loader is merged (#436) and presumably has different, exciting problems. Feel free to re-open!
